### ISSUE TITLE
FileSystemAlreadyExistsException

### ISSUE THREAD

**Issue by m4caron** [anskaffelser/vefa-validator#41]
Please make sure these boxes are checked before submitting your issue - thank you!

- [x ] Issue is not related to specific validation rules for any domain.
- [x ] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
I am occasionally getting this exception when creating multiple instances of the validator one after another.
Previous instance is always closed with the close() method. Error occurs randomly and is hard to debug.

It is happening in version 2.0.2

java.lang.RuntimeException: Unable to create VEFA Validator instance at no.hafslund.automated.HafslundRunnerV2.runClass(HafslundRunnerV2.java:321) at no.hafslund.automated.HafslundRunnerV2.(HafslundRunnerV2.java:105) at no.hafslund.automated.HafslundRunnerV2.main(HafslundRunnerV2.java:563) Caused by: java.nio.file.FileSystemAlreadyExistsException: jimfs://vefa at com.google.common.jimfs.JimfsFileSystemProvider.newFileSystem(JimfsFileSystemProvider.java:114) at no.difi.vefa.validator.source.AbstractSourceInstance.(AbstractSourceInstance.java:56) at no.difi.vefa.validator.source.DirectorySourceInstance.(DirectorySourceInstance.java:36) at no.difi.vefa.validator.source.DirectorySource.createInstance(DirectorySource.java:27) at no.difi.vefa.validator.ValidatorInstance.(ValidatorInstance.java:72) at no.difi.vefa.validator.Validator.load(Validator.java:126) at no.difi.vefa.validator.ValidatorBuilder.build(ValidatorBuilder.java:188) at no.hafslund.automated.steps.validators.ehf.ValidateEHF2.start(ValidateEHF2.java:155) at no.hafslund.automated.steps.validators.ehf.ValidateEHF2.init(ValidateEHF2.java:78) at no.hafslund.automated.HafslundRunnerV2.runClass(HafslundRunnerV2.java:265) ... 2 more

**Comment by klakegg** [comment]
Solved by removing Jimfs in next release.
