### ISSUE TITLE
Unknown document type

### ISSUE THREAD

**Issue by AlexandruCiobanu** [anskaffelser/vefa-validator#51]
Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] Issue is not related to specific validation rules for any domain.
- [ X] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
When I try the sample you proviced in the description with an invoice xml I get "Unknown document type". I saw a thread pertaining to EHF validation and even following the steps there did not get me past the error.
This is very unfortunate as this project seems really awesome. I wish you would consider maintaining it further.

**Comment by klakegg** [comment]
Unable to reproduce.
