### ISSUE TITLE
Problems loading validator

### ISSUE THREAD

**Issue by adammscisz** [anskaffelser/vefa-validator#52]
Since yesterday Validator won't load. Both 2.0.1 and 2.0.2

`Exception in validation core, have to exit : Unable to load validator.
no.difi.vefa.validator.api.ValidatorException: Unable to load validator.`

**Comment by adammscisz** [comment]
Update: 2.0.2 started working, 2.0.1 still fails on loading validator.

**Comment by klakegg** [comment]
"Exception in validation core, have to exit :" indicate wrapping of the validator in your own code. Due to lack of stack trace is it difficult to guess what happend.
