### ISSUE TITLE
Feature Request: Web API 

### ISSUE THREAD

**Issue by esbenbach** [anskaffelser/vefa-validator#53]
Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] Issue is not related to specific validation rules for any domain.
- [ ] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
This may not be the correct channel, but I will give it a shot.
We generate EHF files and would very much like to be able to automatically test our generator against the validator, we would ALSO like to do runtime validation when producing files. 
However as there is no such thing as Java in our runtime environments (or dev environments for that matter) - it would be just about awesome if we could use the online validator at https://vefa.difi.no/validator/ through some sort of Web API.

We can fake the file upload as it is but its not really ideal, and I guess the site is not scaled for that type of use regardless.

Anyway, it would be a welcome addition.

**Comment by klakegg** [comment]
None of the boxes seem to be checked.
