### ISSUE TITLE
Inconsistency between vefavalidator and EHF3 Docs

### ISSUE THREAD

**Issue by agvald** [anskaffelser/vefa-validator#54]
Please make sure these boxes are checked before submitting your issue - thank you!

- [x] Issue is not related to specific validation rules for any domain.
- [x] Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

Your issue here:
1. Based on the documentation from https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/tree/ and https://docs.peppol.eu/poacc/billing/3.0/bis/#_allowances_and_charges
we should be able to send AdditionalDocumentReference/DocumentTypeCode, TaxTotal/TaxSubtotal/TaxExemptionReason and AllowanceCharge/BaseAmount.

2. Vefa validator validates that AllowanceCharge/BaseAmount should be present when AllowanceCharge/MultiplierFactorNumeric is present. At the same time it validates that AllowanceCharge/BaseAmount shouldn't be there.

When we try to validate the EHF 3.0 invoice we get xsd validation errors. (original.xml)
![Screen Shot 2019-12-23 at 14 22 10](https://user-images.githubusercontent.com/8139114/71360305-afe82880-258f-11ea-9887-4af540dafd75.PNG)
after removing the AdditionalDocumentReference/DocumentTypeCode(step1.xml)
![Screen Shot 2019-12-23 at 14 23 32](https://user-images.githubusercontent.com/8139114/71360340-d908b900-258f-11ea-980a-5c6c19ed6c2b.PNG)
after removing AllowanceCharge/BaseAmount(step2.xml)
![Screen Shot 2019-12-23 at 14 27 30](https://user-images.githubusercontent.com/8139114/71360563-972c4280-2590-11ea-8b5d-071ae1a4d249.PNG)
after removing TaxTotal/TaxSubtotal/TaxExemptionReasonCode(step3.xml)
![Screen Shot 2019-12-23 at 14 29 58](https://user-images.githubusercontent.com/8139114/71360624-c0e56980-2590-11ea-992f-55e330e3cc53.PNG)

Looks like it is using ubl-invoice-2.1 xsd on the three first pictures, Maybe that causes the issue?

Xmls: 
[ehf3.tar.gz](https://github.com/anskaffelser/vefa-validator/files/3995142/ehf3.tar.gz)

**Comment by klakegg** [comment]
> Please make sure these boxes are checked before submitting your issue - thank you!
> 
> * [x]  Issue is not related to specific validation rules for any domain.
> * [x]  Issue is related to process of validation itself, ie. preparation of validation artifacts and detecting type of content.

This issue seems to be very much related to specific validation rules, thus not relevant in this project.

**Comment by agvald** [comment]
@klakegg 
Where can i find out if I should support sending DocumentTypeCode or not?
The docs shows that we should be able to send it:  https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-AdditionalDocumentReference/cbc-DocumentTypeCode/
while as described in the issue, the validator rejects it.
