### ISSUE TITLE
Critical error thrown

### ISSUE THREAD

**Issue by Tickstar** [anskaffelser/vefa-validator#56]
We reported the following to to Peppol's Helpdesk (https://openpeppol.atlassian.net/browse/PEPPOL-2271). The same issue was then forwarded to https://github.com/ConnectingEurope/eInvoicing-EN16931/issues/202.

_The validation rule https://docs.peppol.eu/poacc/billing/3.0/rules/BR-E-09/ for BIS 3 Credit Note causes a CRITICAL validation error in VEFA Validator when the value equals -0.00._

_If anything, we believe a WARNING would be more fair if this rule remains and it would be good to throw an error that informs the user about the details to why the error was triggered._

Seems as error thrown by Vefa is purely caused by how Vefa interprets the rule and not the rule itself.

**Comment by klakegg** [comment]
None of the expected boxes seems to be checked.
