### ISSUE TITLE
Where to find updated validation artifacts in *.asice file format nowadays

### ISSUE THREAD

**Issue by cdruschk** [anskaffelser/vefa-validator#60]
Please make sure these boxes are checked before submitting your issue - thank you!

- [ ] Fixing my submitted issue is done by making changes to code in this repository.

Your issue here:
First of all I wonder if you still provide the validation artifacts for the VEFA validator in *.asice file format for those who have implemented the validator on their end. Secondly, if that is the case, I need to know how we are supposed to retrieve those artifacts when a new revision has been released. Previously we could download the updated files from https://test-vefa.difi.no/validator/repo/There they are not updated anylonger and browsing to https://anskaffelser.dev/repo/validator/current/ doesn't help either. If I try to access https://anskaffelser.dev/repo/validator/current/ with Github client then I shall provide a user name and password which I don't have. 
So how can we now get hold of the updated *.asice files?

**Comment by klakegg** [comment]
1. The box is not checked.
2. This is clearly not the address you were directed to use.

**Comment by aaron-kumar** [comment]
@cdruschk  : you can find artifacts here : https://anskaffelser.dev/repo/validator/current/artifacts.xml 
e.g. you can download "ehf-stylesheet-9c9a4c4944c4857fa0f45af76bc3aa59c95f551a.asice" as https://anskaffelser.dev/repo/validator/current/ehf-stylesheet-9c9a4c4944c4857fa0f45af76bc3aa59c95f551a.asice  from https://anskaffelser.dev/repo/validator/current/ i.e. just append path and file of each .asice file after https://anskaffelser.dev/repo/validator/current/

NOTE: Download each file and maintain complete folder structure as mentioned.

**Comment by JesMat** [comment]
The Difi team is being helpful as always I see. 

If anyone else stumbles upon this issue: I made a simple Python script that downloads all current .asice files. 
Feel free to use it however you want. 

[Download Difi ASICE files.txt](https://github.com/anskaffelser/vefa-validator/files/6350978/Download.Difi.ASICE.files.txt)
Rename .txt -> .py
