### ISSUE TITLE
Validation fails for The Norwegian Tax Administration

### ISSUE THREAD

**Issue by adrianSoria** [anskaffelser/vefa-validator#65]
The Norwegian Tax Administration  have been using DIFI validation and rendering since 2016.
Our solution no longer works in test. We get the following error :

`<assertion identifier="SYSTEM-003" flag="fatal"> <text>Unable to find validation configuration based on ProfileId and CustomizationId. (Configuration for 'urn:www.cenbii.eu:profile:bii04:ver2.0#urn:www.cenbii.eu:transaction:biitrns010:ver2.0:extended:urn:www.peppol.eu:bis:peppol4a:ver2.0:extended:urn:www.difi.no:ehf:faktura:ver2.0' not found)</text>
`

We are using version 2.0.2
Did anything change on your end ?

**Comment by klakegg** [comment]
1. Version 2.0.2 was superseeded almost two years ago. We are not plannen to release a version 2.0.3.
2. The reporting does not contain enough information for reproduction.
3. The Norwegian Tax Administration is not "special" enough to not use the issue template of this project.
