### ISSUE TITLE
Update eForms version in a validator?

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/vefa-validator#71]
A validator at https://anskaffelser.dev/service/validator supports version 1.3 of eForms which is quite obsolete today.
Could you upgrade your validator to the 'latest' version you expect to use?

**Comment by klakegg** [comment]
I see you did remove the template provided for issues in this repository, clearly indicating you understand the issue raised doesn't belong here.

**Comment by eduardsmirnov** [comment]
Thank you, very helpful answer.
