### ISSUE TITLE
How to run validator locally?

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/vefa-validator#75]
As online validator ( https://anskaffelser.dev/service/validator/ ) is often not available, error 504, could you give direction how to run this project on a local computer?
I am not Java developer, called command "mvn install" which created me some jar file which I cannot execute.

**Comment by klakegg** [comment]
Then I suggest you get in contact with a Java developer.

**Comment by eduardsmirnov** [comment]
Thank you, very helpful answer.
