### ISSUE TITLE
What is wrong with XML file?

### ISSUE THREAD

**Issue by eduardsmirnov** [anskaffelser/vefa-validator#76]
What is wrong with XML file?
Should be EU notice, subtype 1. Seems to be passed local validation (schema + xslt) but getting success=false from validation API (https://dof-notices-dev-api.azure-api.net/api/v2/notice/notices/validate)

`<PriorInformationNotice xmlns:cac="urn:oasis:names:specification:ubl:schema:xsd:CommonAggregateComponents-2" xmlns:cbc="urn:oasis:names:specification:ubl:schema:xsd:CommonBasicComponents-2" xmlns:ext="urn:oasis:names:specification:ubl:schema:xsd:CommonExtensionComponents-2" xmlns:efac="http://data.europa.eu/p27/eforms-ubl-extension-aggregate-components/1" xmlns:efext="http://data.europa.eu/p27/eforms-ubl-extensions/1" xmlns:efbc="http://data.europa.eu/p27/eforms-ubl-extension-basic-components/1" xmlns="urn:oasis:names:specification:ubl:schema:xsd:PriorInformationNotice-2">
  <ext:UBLExtensions>
    <ext:UBLExtension>
      <ext:ExtensionContent>
        <efext:EformsExtension>
          <efbc:TransmissionDate>2023-08-28+00:00</efbc:TransmissionDate>
          <efbc:TransmissionTime>13:53:52+00:00</efbc:TransmissionTime>
          <efac:NoticeSubType>
            <cbc:SubTypeCode listName="notice-subtype">1</cbc:SubTypeCode>
          </efac:NoticeSubType>
          <efac:Organizations>
            <efac:Organization>
              <efac:Company>
                <cac:PartyIdentification>
                  <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
                </cac:PartyIdentification>
                <cac:PartyName>
                  <cbc:Name languageID="NOR">Buyer 1</cbc:Name>
                </cac:PartyName>
                <cac:PartyName>
                  <cbc:Name languageID="ENG">Buyer 1</cbc:Name>
                </cac:PartyName>
                <cac:PostalAddress>
                  <cbc:CityName>Oslo</cbc:CityName>
                  <cac:Country>
                    <cbc:IdentificationCode listName="country">NOR</cbc:IdentificationCode>
                  </cac:Country>
                </cac:PostalAddress>
                <cac:PartyLegalEntity>
                  <cbc:CompanyID schemeID="002">b1</cbc:CompanyID>
                </cac:PartyLegalEntity>
                <cac:Contact>
                  <cbc:Name>Touchpint 1</cbc:Name>
                  <cbc:Telephone>+37212345678</cbc:Telephone>
                  <cbc:ElectronicMail>mail@mail.mm</cbc:ElectronicMail>
                </cac:Contact>
              </efac:Company>
            </efac:Organization>
          </efac:Organizations>
        </efext:EformsExtension>
      </ext:ExtensionContent>
    </ext:UBLExtension>
  </ext:UBLExtensions>
  <cbc:UBLVersionID>2.3</cbc:UBLVersionID>
  <cbc:CustomizationID>eforms-sdk-1.7#extended#urn:fdc:anskaffelser.no:2023:eforms:eu</cbc:CustomizationID>
  <cbc:ID schemeName="notice-id">70dae2db-28db-4cab-baa2-d9fb00db9687</cbc:ID>
  <cbc:IssueDate>2023-08-28+00:00</cbc:IssueDate>
  <cbc:IssueTime>12:48:52+00:00</cbc:IssueTime>
  <cbc:VersionID>01</cbc:VersionID>
  <cbc:RegulatoryDomain>32014L0024</cbc:RegulatoryDomain>
  <cbc:NoticeTypeCode listName="planning">pin-buyer</cbc:NoticeTypeCode>
  <cbc:NoticeLanguageCode>NOR</cbc:NoticeLanguageCode>
  <cac:AdditionalNoticeLanguage>
    <cbc:ID>ENG</cbc:ID>
  </cac:AdditionalNoticeLanguage>
  <cac:ContractingParty>
    <cbc:BuyerProfileURI>https://buyer1.bb</cbc:BuyerProfileURI>
    <cac:ContractingPartyType>
      <cbc:PartyTypeCode listName="buyer-legal-type">body-pl-la</cbc:PartyTypeCode>
    </cac:ContractingPartyType>
    <cac:ContractingActivity>
      <cbc:ActivityTypeCode listName="authority-activity">econ-aff</cbc:ActivityTypeCode>
    </cac:ContractingActivity>
    <cac:Party>
      <cac:PartyIdentification>
        <cbc:ID schemeName="organization">ORG-0001</cbc:ID>
      </cac:PartyIdentification>
    </cac:Party>
  </cac:ContractingParty>
  <cac:ProcurementProject>
    <cbc:Name languageID="NOR">Main title</cbc:Name>
    <cbc:Name languageID="ENG">Main title</cbc:Name>
    <cbc:Description languageID="NOR">Main description...</cbc:Description>
    <cbc:Description languageID="ENG">Main description...</cbc:Description>
    <cbc:ProcurementTypeCode listName="contract-nature">supplies</cbc:ProcurementTypeCode>
    <cac:MainCommodityClassification>
      <cbc:ItemClassificationCode listName="cpv">03000000</cbc:ItemClassificationCode>
    </cac:MainCommodityClassification>
  </cac:ProcurementProject>
</PriorInformationNotice>`

**Comment by klakegg** [comment]
I see you did remove the template provided for issues in this repository, clearly indicating you understand the issue raised doesn't belong here.

**Comment by eduardsmirnov** [comment]
Thank you, very helpful answer.
